# Application
quarkus.application.name=djinn
quarkus.http.port=38797

quarkus.index-dependency.2next.group-id=io.kneo
quarkus.index-dependency.2next.artifact-id=2next

# Logging
quarkus.log.level=INFO

# Scheduler
quarkus.scheduler.enabled=true

# Health Checks
quarkus.smallrye-health.enabled=true

# Optionally disable Dev UI entirely (comment out if you want Dev UI)
# quarkus.devui.enabled=false

# Suppress verbose FFmpeg wrapper output
quarkus.log.category."net.bramp.ffmpeg".level=WARN
quarkus.log.category."net.bramp.ffmpeg.builder".level=ERROR
quarkus.log.category."net.bramp.ffmpeg.RunProcessFunction".level=ERROR

# RabbitMQ Messaging Configuration
rabbitmq-host=localhost
rabbitmq-port=5672

mp.messaging.outgoing.queue-requests.connector=smallrye-rabbitmq
mp.messaging.outgoing.queue-requests.exchange.name=queue-requests
mp.messaging.outgoing.queue-requests.exchange.type=topic
mp.messaging.outgoing.queue-requests.queue.name=queue-requests
mp.messaging.outgoing.queue-requests.queue.declare=true
mp.messaging.outgoing.queue-requests.exchange.declare=true
